import org.gradle.api.initialization.resolve.RepositoriesMode

pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven {
            // needed for netlayer packages
            url = 'https://jitpack.io'
            content {
                includeGroup('com.github.bisq-network.netlayer')
                includeGroup('com.github.bisq-network.tor-binary')
                includeGroup('com.github.bisq-network')
            }
        }
        mavenCentral()
    }
}

rootProject.name = 'tor-spring-boot-starter'

include 'spring-tor:spring-tor-core'
include 'spring-tor:spring-tor-hidden-service'
include 'spring-tor:spring-tor-http-client'
include 'spring-tor:spring-tor-autoconfigure'
include 'spring-tor:spring-tor-starter'
include 'spring-tor:spring-tor-example-application'

// deprecated in favor of module spring-tor-http-client
include 'spring-tor:spring-tor-http'
